import {clamp,dist} from '../core.js';import {clouds,unicorns,game,debug} from '../state.js';import {lightningImpact} from './effects.js';import {startRain} from './weather.js';
export function getCurrentTarget(){return game.rescued>=unicorns.length?null:unicorns[game.rescued]}export function getArrowUI(){const t=getCurrentTarget();return t?t.ui:Infinity}export function canCollideCloud(c){if(debug.blackCloud&&c.black)return true;return c.hp>=getArrowUI()}
export function segmentCircle(x1,y1,x2,y2,cx,cy,radius){const dx=x2-x1,dy=y2-y1,len2=dx*dx+dy*dy;if(len2===0)return dist(x1,y1,cx,cy)<=radius;let t=((cx-x1)*dx+(cy-y1)*dy)/len2;t=clamp(t,0,1);return dist(x1+dx*t,y1+dy*t,cx,cy)<=radius}
export function fadeCloud(c){if(c.black)return;c.hp=Math.max(0,c.hp-1);c.ui=c.hp;c.opacity=clamp(c.hp/c.maxHP,.08,1);c.flash=1}
export function condenseCloud(c){c.hp=Math.min(c.maxHP+1,c.hp+1);c.ui=c.hp;c.opacity=1;c.black=true;c.lightningTimer=performance.now()+rndLocal(300,1000);c.lightningFlash=1;lightningImpact(c.x,c.y)}function rndLocal(a,b){return a+Math.random()*(b-a)}
export function restoreBlackClouds(){for(const c of clouds){if(!c.black)continue;c.black=false;c.hp=Math.min(c.hp,c.maxHP);c.ui=c.hp;c.opacity=clamp(c.hp/c.maxHP,.08,1);c.lightningFlash=0;c.flash=1}}
export function hitCloud(c){if(!debug.blackCloud){fadeCloud(c);game.score+=1;lightningImpact(c.x,c.y);return}if(c.black){c.lightningFlash=1;c.flash=1;game.score+=1;lightningImpact(c.x,c.y);return}if(Math.random()<.25)condenseCloud(c);else fadeCloud(c);game.score+=1;lightningImpact(c.x,c.y)}
export function rescue(u){if(u.rescued||u.id!==game.rescued)return;u.rescued=true;game.score+=100+u.id*25;game.rescued++;lightningImpact(u.x,u.y);if(debug.blackCloud)restoreBlackClouds();startRain(u);if(game.rescued>=unicorns.length)setTimeout(()=>{game.finished=true;document.getElementById('finalScore').textContent='最终得分：'+game.score;document.getElementById('finish').classList.add('show')},1900)}
export function checkCollision(arrow,oldX,oldY){const target=getCurrentTarget();if(!target)return false;let nearest=null,nearestDistance=Infinity;for(const c of clouds){if(c.hp<=0&&!c.black)continue;if(!canCollideCloud(c))continue;if(segmentCircle(oldX,oldY,arrow.x,arrow.y,c.x,c.y,c.radius)){const d=dist(oldX,oldY,c.x,c.y);if(d<nearestDistance){nearestDistance=d;nearest=c}}}if(nearest){hitCloud(nearest);return true}if(segmentCircle(oldX,oldY,arrow.x,arrow.y,target.x,target.y,target.radius)){rescue(target);return true}return false}
